name: Deploy to Hostinger VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            chown -R taw10:taw10 /home/taw10/taw10
            sudo -i -u taw10 bash << 'EOF'
            cd /home/taw10/taw10
            git config --global --add safe.directory /home/taw10/taw10
            git fetch origin
            git reset --hard origin/main
            
            # 1. Backend build & deploy
            cd /home/taw10/taw10/backend
            npm install
            npx prisma generate
            npx prisma db push --accept-data-loss
            npm run build
            pm2 restart taw10-backend
            
            # 2. Frontend build & deploy
            cd /home/taw10/taw10/frontend
            npm install
            npm run build
            pm2 restart taw10-frontend
            EOF
